### ISSUE TITLE
Building Android + OPTEE for Hikey960

### ISSUE THREAD

**Issue by a2t2** [linaro-swg/optee_android_manifest#20]
I am trying to setup a Android + OPTEE branch to flash a Hikey 960. I need to have both userspace and kernel built from source.
So far, I have tested the AOSP userspace [build instructions](https://source.android.com/source/devices#960userspace), which works fine.
When I try to sync Android + OPTEE, I cannot find the build option for Hikey960. I tried as follows (I combined instructions from Google's site and Android + OPTEE Manifest):

```
$ repo init -u https://android.googlesource.com/platform/manifest -b master
$ cd .repo
$ git clone https://github.com/linaro-swg/optee_android_manifest.git local_manifests
$ cd ..
$ repo sync -j24
$ wget https://dl.google.com/dl/android/aosp/arm-hikey960-NOU-7ad3cccc.tgz
$ tar xzf arm-hikey960-NOU-7ad3cccc.tgz
$ ./extract-arm-hikey960.sh
```

After this if I try the following, I cannot find the build option for Hikey 960 (I get the error `Don't have a product spec for: hikey960-userdebug`):

```
$ . ./build/envsetup.sh
$ lunch hikey960-userdebug
```

Any suggestions on how to fix this ? 
Can I just add the hikey960-userdebug lunch_combo to vendorsetup.sh ? Will that work ?

Thanks

**Comment by vchong** [comment]
OP-TEE is not supported yet on hikey960 android. It might be a while before it is.

**Comment by a2t2** [comment]
Can you give me a time frame when it might get support ? Thanks.

**Comment by a2t2** [comment]
Can you let me know any URL where OPTEE support for hikey 960 will be announced once its done ? I want to check periodically. Will the the AOSP+OP-TEE manifest github page be updated when that happens? Thanks

**Comment by vchong** [comment]
Yes, the manifest github page will be updated but there will be no url or announcement so you'll just have to manually check it periodically. Sorry. I'll make a note to post an update here when support is ready but as mentioned before, it might be a while since this task is currently on the backlog as there are other higher priority tasks atm.

**Comment by a2t2** [comment]
Okay thanks.

**Comment by rabi2017** [comment]
Hi @vchong ,
Does OP-TEE with AOSP build is available for hikey 960 boards with hardware decoding support?

Thanks,
Rabi

**Comment by vchong** [comment]
@rabi2017 Afaik the regular hikey960 aosp build hasn't implemented hw decoding support yet. You can track patches here [1] to see when/if they come up. Also, there's not really a proper hikey960 aosp with op-tee build yet since development is currently inactive due to other priorities. You can try an 'informal' build here [2] if you want but not sure how stable it is.

[1] https://android-review.googlesource.com/q/project:device%252Flinaro%252Fhikey
[2] https://github.com/vchong/optee_android_manifest/blob/wip/tmp.txt

**Comment by vchong** [comment]
One of our community users, @bensup, has kindly shared his implementations here: https://github.com/bsupiot/hikey960-aosp-optee/wiki. For those who are interested, please give it a try. There are some known issues so please contribute back patches if possible. A big thank you to @bensup! Thanks!

**Comment by vchong** [comment]
@a2t2 You can try hikey960 build on https://github.com/linaro-swg/optee_android_manifest now.
