### ISSUE TITLE
some thoughts about secure issue using Hikey960

### ISSUE THREAD

**Issue by BeitongT** [linaro-swg/optee_android_manifest#48]
I am thinking how can we perform remote attestation on hikey960. Normally, we cannot unlock the boot loader and change the OS in our Android Device. But in hikey960, we can customize the whole system.   For example, if we are using some geo-fencing app like Pokemon Go. Can we customize the system to provide fake GPS location to the server? Is it durable? Or the Pokemon Go app can use some remote attestation methods to detect that we are abusing this device and refuse the service?

**Comment by vchong** [comment]
@BeitongT This is sort of out-of-scope of what we're doing/providing here, so you might want to take the following comments with a grain of salt. It appears that there are attestation APIs (https://developer.android.com/training/safetynet/attestation) that apps can use to check the integrity of a device, but whether Pokemon Go uses them is a separate issue. These APIs would presumably call down to lower level functions in the OS and/or bootloader/firmware. Since you have control of OS and bootloader on the device, I suppose you can maybe try to add some prints (or use whatever debugging tools available to you) to monitor the system to see what exactly is going on, and make the changes you want.
