### ISSUE TITLE
Errors on flashing Hikey960

### ISSUE THREAD

**Issue by tesmnorth** [linaro-swg/optee_android_manifest#51]
Hello, 
today, I tried to install optee_android to Hikey960. I builded optee-android successfully.
But, there are some errors while flashing some images.
Firstly, there is an error like this: 
```
android out dir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
flashing recovery images.. please wait ~10 seconds
Config name: config
Port name: /dev/ttyUSB0
Error when open file config
```
For this error, I tried to add `"${INSTALLER_DIR}"/`  to `-c` parameter :
`sudo "${INSTALLER_DIR}"/hikey_idt -c "${INSTALLER_DIR}"/config -p "${DEVICE_PORT}"`
Then it works but there is another error like this: 

```
android out dir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
flashing recovery images.. please wait ~10 seconds
Config name: ./device/linaro/hikey/installer/hikey960/config
Port name: /dev/ttyUSB0
0: Image: ./hisi-sec_usb_xloader.img Downalod Address: 0x20000
1: Image: ./hisi-sec_uce_boot.img Downalod Address: 0x6a908000
2: Image: ./recovery.bin Downalod Address: 0x1ac00000
Serial port open successfully!
Start downloading ./hisi-sec_usb_xloader.img@0x20000...
Error when open file ./hisi-sec_usb_xloader.img
./device/linaro/hikey/installer/hikey960/flash-all.sh: line 56: 14853 Segmentation fault      sudo "${INSTALLER_DIR}"/hikey_idt -c "${INSTALLER_DIR}"/config -p "${DEVICE_PORT}"
```

For this error, I changed config file like this:

```
/home/xx/optee_android_manifest/device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img 0x00020000
/home/xx/optee_android_manifest/device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img 0x6A908000
/home/xx/optee_android_manifest/device/linaro/hikey/installer/hikey960/recovery.bin 0x1AC00000
```
Then error is fixed and flashing successfully. 
I write it for understandable issue. Maybe it is wrong maybe not. (But xtest result is totally success)

Another thing is that screen is not working on hikey960. I need to make something for this?
Edit: I think my question is about this warning while building:
```
device/linaro/hikey/hikey960/device-hikey960.mk:87: warning: TARGET_HISI_CODEC_VERSION () does not match exiting the build (1).
device/linaro/hikey/hikey960/device-hikey960.mk:88: warning: Please download new binaries here:
device/linaro/hikey/hikey960/device-hikey960.mk:89: warning: https://dl.google.com/dl/android/aosp/hisilicon-hikey960-OPR-3c243263.tgz 
device/linaro/hikey/hikey960/device-hikey960.mk:90: warning: And extract in the ANDROID_TOP_DIR
```

Thanks

**Comment by vchong** [comment]
@tesmnorth Thanks for reporting! I made some changes. Please try again from `sync-p-hikey960.sh`.

**Comment by vchong** [comment]
@tesmnorth Please `rm /home/xx/optee_android_manifest/abc` before running `sync-p-hikey960.sh`.

**Comment by tesmnorth** [comment]
@vchong I tried it. But, now hikey960 doesnt work in no way.

**Comment by vchong** [comment]
@tesmnorth seems like a kernel issue, not op-tee. Working on a workaround while waiting for the fix by the right people. In the meantime, you can:
```
wget http://snapshots.linaro.org/android/android-hikey960-optee-p/92/boot.img.xz
unxz boot.img.xz
sudo fastboot flash boot boot.img
```

Btw, for future reference, please provide more details about the issue you're having. It's hard to figure out what 'doesn't work in no way' really means.

**Comment by tesmnorth** [comment]
@vchong I mean that hikey960 can not boot. Secondly, How can I understand to fix by the right people? 

Problem is continuing. LCD screen shows black screen and Hikey960 is closing by itself

**Comment by jockebech** [comment]
> How can I understand to fix by the right people?

That is never easy, when things like this happens to me I usually.
1) Do a quick search on Google to see if something similar shows up.
2) Try to have a look at the error message to identify where things are going wrong.
3) See if I can figure out the problem and solve it myself by submitting a patch to that particular project.
4) If "3" isn't something I can do, then I typically send a question on the projects forum. Here include as much as you can, how did you run it, what have you compiled, what are the error messages etc.
5) If there is no such forum or email available, then I will send it to the one that put together the instructions (like what you've done here).

As said, it's not easy and not straight forward, but with experience it gets easier.

Btw, AOSP is extra complicated since the project consists of several hundred individual software components. Compare that with a plain OP-TEE on Linux where it's usually enough with 7-10 gits to make a fully working system.

**Comment by tesmnorth** [comment]
thank you for your information @jbech-linaro. I think, screen problem is also related to AOSP. I think, I need to wait it.

**Comment by tesmnorth** [comment]
@vchong Can I build optee with Android 8 for resolving screen problem? I looked into "archieve" folder. All xml files includes android 9. Is Android 8 possible right now?

**Comment by vchong** [comment]
@tesmnorth Kernel issue is fixed by the kernel developers. I don't have/know the details. You can try rebuilding again from scratch to see if it boots ok now. In any case, that boot problem shouldn't be related to your screen issue. We haven't experienced any screen issues here with our hdmi monitor. The GUI looks fine. After the device boots up, run `getprop | grep sys.logbootcomplete` in your console. If you see `1`, that means you've booted to the home screen and your monitor might not be compatible with the board. You can try the suggestion you got on the 96boards forum to lower the output resolution to see if that helps.

> Can I build optee with Android 8 for resolving screen problem? I looked into "archieve" folder. All xml files includes android 9. Is Android 8 possible right now?

You can try the `sync-o.sh` and `build-o.sh` script, but sorry to say that we don't support it anymore and won't be able to help should there be any further issues or problems. In fact, once OP-TEE 3.4.0 is released, we'll be reverting to supporting a single fixed release version only, i.e. Android 9 at this point, and update the release every quarter or half. All the various combinations of builds have proven to be too costly to support continuously. Thanks for your understanding.

**Comment by tesmnorth** [comment]
@vchong My screen is working with my hikey620 board. Also it is working with hikey960. But, I didnt try hikey960 with optee_android manifest. I tried just android.

> You can try rebuilding again from scratch to see if it boots ok now.

I need to rebuild after everything is deleted and re-again? If not, `./sync-p-hikey960.sh` is enough without deleting everything?

**Comment by vchong** [comment]
> I didnt try hikey960 with optee_android manifest. I tried just android.

"hikey960 with optee_android manifest" is Android 9. I'm guessing "just android" is master build? Maybe something's lacking in v9 to support the screen.

> I need to rebuild after everything is deleted and re-again? If not, ./sync-p-hikey960.sh is enough without deleting everything?

`rm -rf out && ./sync-p-hikey960.sh`

**Comment by tesmnorth** [comment]
> We haven't experienced any screen issues here with our hdmi monitor. The GUI looks fine. 

@vchong I know you haven't experienced any screen issues. But, I have one more question maybe you have any suggestion about that.

What about adding `video=HDMI-A-1:800x480@60 ` to kernel commandline? Can it work?

> I'm guessing "just android" is master build? 

It is Android 8. :/

**Comment by vchong** [comment]
> What about adding video=HDMI-A-1:800x480@60 to kernel commandline? Can it work?

That's what I meant earlier by "You can try the suggestion you got on the 96boards forum to lower the output resolution to see if that helps". Under `device/linaro/hikey/hikey960/BoardConfig.mk`, you'll see something like:
```
BOARD_KERNEL_CMDLINE := androidboot.hardware=hikey960 console=ttyFIQ0 androidboot.console=ttyFIQ0
BOARD_KERNEL_CMDLINE += video=vfb:640x480-32@30 vfb.videomemorysize=3145728
BOARD_KERNEL_CMDLINE += firmware_class.path=/vendor/firmware loglevel=15 efi=noruntime
```
You can remove the existing `video=...` settings and replace it with yours instead, but since we don't have your screen, we can't really say for sure whether it'll work or not.

> It is Android 8.

Afaik, hikey960 support isn't available in Android 8.

**Comment by tesmnorth** [comment]
I tried them. but screen is not displayed android gui.

**Comment by tesmnorth** [comment]
Hello @vchong, 

I took a suggestion from 96boards forum. Is it possible to add a driver patch to optee_android_manifest?
Related topic from 96boards.org : https://discuss.96boards.org/t/hikey960-screen-problem/7136/22?u=tesmnorth

**Comment by vchong** [comment]
@tesmnorth As I'd noted on the forum, from the patch description, 4.14 might not need it, but since it doesn't do any harm, I've added it to the build. You can try rebuilding to see if it helps.
