### ISSUE TITLE
How to compile secure world individually？

### ISSUE THREAD

**Issue by liyc0927** [linaro-swg/optee_android_manifest#65]
Hi there ! 
First thank you very much ! Under your guidance , I have built Android 9.0 and optee on Hikey960 ,  and I run xtest with 0 fail.
One thing I wonder is that how to compile secure world part ( such as optee_os , arm-trusted-firmware , etc. ) individually and flash changes into hikey960 when only those parts are changed , cause it costs too much time to build the whole system . The situation can be : 
1. I change somewhere of optee_os ; 
2. I want to add a TA into system . 
I read the [build](https://optee.readthedocs.io/building/gits/build.html) section of OP-TEE gits , but it seems to aim at building a independent OP-TEE project and does not work in this case . 
So how can I do it ? 
Thanks in advance .

**Comment by liyc0927** [comment]
I found the answer of situation 2 [here](https://github.com/linaro-swg/optee_android_manifest/issues/14) 
Thanks a lot !

**Comment by vchong** [comment]
You're welcome.

> how to compile secure world part ( such as optee_os , arm-trusted-firmware , etc. ) individually

If you're using `optee_android_manifest`'s build scripts, then try `./build-p.sh out/dist/fip.bin`. There's no granularity to build single components within optee_os, arm-trusted-firmware, etc. I don't think.

If you want to build just the TA, then `./build-p.sh <name of CA or TA>`, provided you have the proper `Android.mk` file. The CA or TA name corresponds to the `LOCAL_MODULE` name in Android.mk. E.g. `./build-p.sh optee_example_hello_world` or `./build-p.sh 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta`.

> flash changes into hikey960 when only those parts are changed

`fastboot flash fip <path/to/>fip.bin`

> it costs too much time to build the whole system

If you'd already built the whole system once, building the whole system again actually takes a lot less time since it should just build anything that's changed, similar to running a regular Makefile or `make` command.

**Comment by liyc0927** [comment]
It works for me, thanks a lot!  @vchong
