### ISSUE TITLE
Hikey AOSP build and python2

### ISSUE THREAD

**Issue by a21152** [linaro-swg/optee_android_manifest#77]
It seems Hikey AOSP (using tag 3.13.0) is failing to build due to python2 in some of the scripts.

Installing python2 does not solve the issue.

How are you getting around the build issue in your quarterly release test builds?

**Comment by jforissier** [comment]
Hi @a21152,

I don't think anyone has been running AOSP tests on the quarterly releases for quite some time (`git log --grep="Tested-by:.*[Aa][Oo][Ss][Pp]"` hints at 3.15.0 in September 2021). But, since you are using an older tag I suppose you should be able to reproduce the build. Maybe you need to run an older OS as a build host in VM or a container?

**Comment by a21152** [comment]
Hi Jerome,

You are right. I was misled by the documentation which still states it is run quarterly. 

https://optee.readthedocs.io/en/latest/building/aosp/aosp.html

I am trying to wade out the errors manually.

Thanks, Ali
